# Lab | Hypothesis Testing

**Objective**

Welcome to the Hypothesis Testing Lab, where we embark on an enlightening journey through the realm of statistical decision-making! In this laboratory, we delve into various scenarios, applying the powerful tools of hypothesis testing to scrutinize and interpret data.

From testing the mean of a single sample (One Sample T-Test), to investigating differences between independent groups (Two Sample T-Test), and exploring relationships within dependent samples (Paired Sample T-Test), our exploration knows no bounds. Furthermore, we'll venture into the realm of Analysis of Variance (ANOVA), unraveling the complexities of comparing means across multiple groups.

So, grab your statistical tools, prepare your hypotheses, and let's embark on this fascinating journey of exploration and discovery in the world of hypothesis testing!

**Challenge 1**

In this challenge, we will be working with pokemon data. The data can be found here:

- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/pokemon.csv

In [1]:
#libraries
import pandas as pd
import scipy.stats as st
import numpy as np

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/pokemon.csv")
df

,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,Mega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...
795,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,Mega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,Hoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,Hoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

- We posit that Pokemons of type Dragon have, on average, more HP stats than Grass. Choose the propper test and, with 5% significance, comment your findings.

In [6]:
print("H0: AverageHP of Type Dragon <= Type Grass")
print("Ha: AverageHP of Type Dragon > Type Grass")
print("")
dragon_hp = df[( df['Type 1'] == 'Dragon') | (df['Type 2'] == 'Dragon')]['HP']  # In case Dragon appeared in type 1 or 2, same with grass
grass_hp  = df[(df['Type 1'] == 'Grass')  | (df['Type 2'] == 'Grass')]['HP']

#Two-sample t-test, one-tailed (alternative='greater' = Dragon > Grass)
t_stat, p_value_two = st.ttest_ind(dragon_hp, grass_hp)
# P_value / 2 since is two tailed
p_value_one = p_value_two / 2

print(f"T-statistic: {t_stat:.4f}")
print(f"P-value (one-tailed): {p_value_one:.4f}")

if p_value_one < 0.05:
    print("We reject the null hypothesis, so Dragons have > HP than grass")
else:
    print("We accept the alternative hypothesis, so Dragons have <= than grass")

print("")
print(f"HP average of Dragon: {dragon_hp.mean():.2f}")
print(f"HP average of Grass: {grass_hp.mean():.2f}")

H0: AverageHP of Type Dragon <= Type Grass
Ha: AverageHP of Type Dragon > Type Grass

T-statistic: 4.4991
P-value (one-tailed): 0.0000
We reject the null hypothesis, so Dragons have > HP than grass

HP average of Dragon: 82.90
HP average of Grass: 66.05

The P-value is almost 0, we can conclude that Dragon type have more HP than grass type

- We posit that Legendary Pokemons have different stats (HP, Attack, Defense, Sp.Atk, Sp.Def, Speed) when comparing with Non-Legendary. Choose the propper test and, with 5% significance, comment your findings.

In [10]:
stats_pok = ["HP", "Attack", "Defense", "Sp. Atk", "Sp. Def", "Speed"]

legendary = df[df["Legendary"] == True]
non_legendary = df[df["Legendary"] == False]

for stat in stats_pok:
    t_stat, p_value = st.ttest_ind(legendary[stat], non_legendary[stat])
    result = "Reject H0" if p_value < 0.05 else "Accept Ha"
    print(f"{stat}: t={t_stat:.4f}, p={p_value:.4f} → {result}")
    print(f"Legendary mean: {legendary[stat].mean():.2f} | Non-Legendary mean: {non_legendary[stat].mean():.2f}")
    print("")

HP: t=8.0361, p=0.0000 → Reject H0
Legendary mean: 92.74 | Non-Legendary mean: 67.18

Attack: t=10.3973, p=0.0000 → Reject H0
Legendary mean: 116.68 | Non-Legendary mean: 75.67

Defense: t=7.1812, p=0.0000 → Reject H0
Legendary mean: 99.66 | Non-Legendary mean: 71.56

Sp. Atk: t=14.1914, p=0.0000 → Reject H0
Legendary mean: 122.18 | Non-Legendary mean: 68.45

Sp. Def: t=11.0378, p=0.0000 → Reject H0
Legendary mean: 105.94 | Non-Legendary mean: 68.89

Speed: t=9.7652, p=0.0000 → Reject H0
Legendary mean: 100.18 | Non-Legendary mean: 65.46

The P_value is close to 0, obviously the Legenday Pokemons have different stats, much stronger in every aspect since they are unique and extremly powerful

**Challenge 2**

In this challenge, we will be working with california-housing data. The data can be found here:
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/california_housing.csv

In [11]:
df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/california_housing.csv")
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

**We posit that houses close to either a school or a hospital are more expensive.**

- School coordinates (-118, 34)
- Hospital coordinates (-122, 37)

We consider a house (neighborhood) to be close to a school or hospital if the distance is lower than 0.50.

Hint:
- Write a function to calculate euclidean distance from each house (neighborhood) to the school and to the hospital.
- Divide your dataset into houses close and far from either a hospital or school.
- Choose the propper test and, with 5% significance, comment your findings.

In [15]:
df.shape

(17000, 9)

In [47]:
print("H0: The houses near a school or a hospital are not more expensive")
print("Ha: The houses near a school or a hospital are more expensive")

H0: The houses near a school or a hospital are not more expensive
Ha: The houses near a school or a hospital are more expensive

In [48]:
def euclidean_distance(long, lat, ref_long, ref_lat):
    return np.sqrt((long-ref_long)**2 + (lat-ref_lat)**2)

df["dist_school"]   = euclidean_distance(df["longitude"], df["latitude"], -118, 34)
df["dist_hospital"] = euclidean_distance(df["longitude"], df["latitude"], -122, 37)
df_school=df[df["dist_school"]<0.5]
df_school

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,dist_school,dist_hospital
2366,-117.51,34.00,36.0,3791.0,746.0,2258.0,672.0,3.2067,124700.0,0.490000,5.400009
2367,-117.51,33.97,35.0,352.0,62.0,184.0,57.0,3.6691,137500.0,0.490918,5.416733
2368,-117.51,33.95,12.0,9016.0,1486.0,4285.0,1457.0,4.9984,169100.0,0.492544,5.427946
2371,-117.52,33.99,14.0,13562.0,2057.0,7600.0,2086.0,5.2759,182900.0,0.480104,5.397268
2372,-117.52,33.89,2.0,17978.0,3217.0,7305.0,2463.0,5.1695,220800.0,0.492443,5.453668
...,...,...,...,...,...,...,...,...,...,...,...
8521,-118.49,34.02,28.0,2545.0,752.0,1548.0,679.0,2.9125,475000.0,0.490408,4.604400
8522,-118.49,34.02,28.0,1394.0,582.0,716.0,543.0,1.5132,450000.0,0.490408,4.604400
8523,-118.49,34.02,27.0,4725.0,1185.0,1945.0,1177.0,4.1365,470800.0,0.490408,4.604400
8524,-118.49,34.01,28.0,651.0,252.0,333.0,174.0,1.9722,500001.0,0.490102,4.610878
8525,-118.49,34.00,32.0,3407.0,1071.0,1463.0,986.0,3.0369,500001.0,0.490000,4.617369

In [49]:
df_hospital= df[df["dist_hospital"]<0.5]
df_hospital

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,dist_school,dist_hospital
12333,-121.51,37.02,19.0,2372.0,394.0,1142.0,365.0,4.0238,374600.0,4.630389,0.490408
12361,-121.53,36.85,23.0,3359.0,725.0,1862.0,651.0,2.6719,193600.0,4.536893,0.493356
12408,-121.56,37.08,17.0,6725.0,1051.0,3439.0,1027.0,6.4313,393100.0,4.707441,0.447214
12419,-121.57,37.02,17.0,2889.0,624.0,2681.0,608.0,2.9417,178000.0,4.676035,0.430465
12420,-121.57,36.98,14.0,5231.0,817.0,2634.0,799.0,4.9702,279800.0,4.650301,0.430465
...,...,...,...,...,...,...,...,...,...,...,...
15090,-122.25,37.08,20.0,1201.0,282.0,601.0,234.0,2.5556,177500.0,5.248705,0.262488
15170,-122.26,37.38,28.0,1103.0,164.0,415.0,154.0,7.8633,500001.0,5.438014,0.460435
15253,-122.27,37.32,37.0,2607.0,534.0,1346.0,507.0,5.3951,277700.0,5.408817,0.418688
15254,-122.27,37.24,30.0,2762.0,593.0,1581.0,502.0,5.1002,319400.0,5.360084,0.361248
15686,-122.38,37.18,52.0,1746.0,315.0,941.0,220.0,3.3047,286100.0,5.412652,0.420476

In [50]:
close = df[(df['dist_school'] < 0.5) | (df['dist_hospital'] < 0.5)]['median_house_value']
far = df[(df['dist_school'] >= 0.5) & (df['dist_hospital'] >= 0.5)]['median_house_value']

print(f"close houses: {len(close)}")
print(f"far houses: {len(far)}")

close houses: 6829
far houses: 10171

In [51]:
5668+1161  # makes sense if we sum the rows of both previous datasets

6829

In [52]:
t_stat, p_two = st.ttest_ind(close, far)
p_one = p_two / 2
print(f"\nT-statistic: {t_stat:.4f}")
print(f"P-value (one-tailed): {p_one:.4f}")

T-statistic: 38.0463
P-value (one-tailed): 0.0000

In [53]:
if p_one < 0.05 and t_stat > 0:
    print("We reject the H0 : The houses near a school or a hospital are not more expensive.")
else:
    print("We accept the Ha: The houses near a school or a hospital are more expensive.")

We reject the H0 : The houses near a school or a hospital are not more expensive.

In [54]:
print("Clean function: ")

Clean function:

In [57]:
print("H0: The houses near a school or a hospital are not more expensive")
print("Ha: The houses near a school or a hospital are more expensive")
print("")
def euclidean_distance(long, lat, ref_long, ref_lat):
    return np.sqrt((long-ref_long)**2 + (lat-ref_lat)**2)

df["dist_school"]   = euclidean_distance(df["longitude"], df["latitude"], -118, 34)
df["dist_hospital"] = euclidean_distance(df["longitude"], df["latitude"], -122, 37)

close = df[(df['dist_school'] < 0.5) | (df['dist_hospital'] < 0.5)]['median_house_value']
far = df[(df['dist_school'] >= 0.5) & (df['dist_hospital'] >= 0.5)]['median_house_value']

print(f"Close houses: {len(close)}")
print(f"Far houses: {len(far)}")

t_stat, p_two = st.ttest_ind(close, far)
p_one = p_two / 2
print(f"\nT-statistic: {t_stat:.4f}")
print(f"P-value (one-tailed): {p_one:.4f}")
print("")
if p_one < 0.05 and t_stat > 0:
    print("We reject the H0, which means that The houses near a school or a hospital are more expensive.")
else:
    print("We accept the Ha, which means that The houses near a school or a hospital are not more expensive.")

H0: The houses near a school or a hospital are not more expensive
Ha: The houses near a school or a hospital are more expensive

Close houses: 6829
Far houses: 10171

T-statistic: 38.0463
P-value (one-tailed): 0.0000

We reject the H0, which means that The houses near a school or a hospital are more expensive.

The p-value is practically 0, we can say that houses near a school or a hospital are more expensive and this doesn't happen by chance